export enum Getters {
    GET_UNICORNS='GET_UNICORNS'
}

export enum Mutations {
    ADD_UNICORN='ADD_UNICORN',
    REMOVE_UNICORN='REMOVE_UNICORN'
}

export enum Actions {
    RETURN_UNICORNS='RETURN_UNICORNS',
    INITIALIZE_STORE='INITIALIZE_STORE'
}